### ISSUE TITLE
track installed apps

### ISSUE THREAD

**Issue by ghost1372** [goranalkovic/WinGetGui#3]
Hello, first of all, thank you for your very good idea
I got an idea from your app and created a similar application
The way you do to check the installed programs is not very good some of them may be pre-installed
I solved this problem with the registry. Most programs are detected
From here you can see the code, It may be useful for you
https://github.com/HandyOrg/HandyWinGet-GUI/blob/f58d10fe293923981e7fff0c96becc533aa4b875/HandyWinGet-GUI/Tools/Tools.cs#L57-L97

**Comment by goranalkovic** [comment]
Currently I'm only tracking apps installed through my app (and I guess throught WinGet).

In the future I don't have plans yet to check if that version of the program is already installed, not sure if I want this to be some kind of an "uninstaller tool", but I'll consider it.

Thanks for the code snippet, it might come in handy 🙂

BTW, I don't see it used in your app as I can install the same package multiple times, and I can install it even if it was installed before, maybe I'm doing something wrong?

**Comment by ghost1372** [comment]
The release version doesn't include this feature yet, but if you build from source you can enable this option from settings and after refreshing list, If there is a pre-installed program, you will see an icon next to it
![Untitled](https://user-images.githubusercontent.com/9213496/82745867-79147980-9d9e-11ea-9365-52f7a419c56d.png)

![2](https://user-images.githubusercontent.com/9213496/82745875-7f0a5a80-9d9e-11ea-9245-e1f07a1487d0.png)

**Comment by goranalkovic** [comment]
Ah ok, got it
